spring:
  application:
    name: hello-world-service
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}